### ISSUE TITLE
Unknown Error verifying age

### ISSUE THREAD

**Issue by ashleykleynhans** [novskey/PalletTown#15]
I attempted to create 320 accounts for RocketMap last night, but only 9 succeeded, and all the others failed with an unknown error verifying age.

[04:58:03]     [DEBUG]:[Worker 2]:  initializing..
[04:58:03]     [DEBUG]:[Worker 2]: Attempting to create user yiftposktob:fL@rsk1zstef. Opening browser...
[04:58:03]     [DEBUG]:[Worker 2]: Proxy type: http
[04:58:03]     [DEBUG]:[Worker 2]: 2captcha key
[04:58:03]     [DEBUG]:127.0.0.1:24003
[04:58:03]     [DEBUG]:Step 1: Verifying age using birthday: 1985-01-24
[04:58:03]     [DEBUG]:[Worker 2]: unknown Error verifying age, terminating
[04:58:03]     [DEBUG]:[Worker 2]: about:blank
[04:58:03]     [DEBUG]:Traceback (most recent call last):
[04:58:03]     [DEBUG]:  File "accountcreate.py", line 373, in <module>
[04:58:03]     [DEBUG]:    create_account(sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4],sys.argv[5],sys.argv[6],sys.argv[7],sys.argv[8],300)
[04:58:03]     [DEBUG]:  File "accountcreate.py", line 229, in create_account
[04:58:03]     [DEBUG]:    raise e
[04:58:03]     [DEBUG]:AssertionError

**Comment by parislarkins** [comment]
Assertion Error means it tried to check the browser was on the correct url but it wasn't, so it terminated. Could be a proxy error or something different. Could you try with no proxy?

**Comment by JoshuaDennisBlackman** [comment]
I am also getting this issue, I have tried multiple different proxies
