### ISSUE TITLE
Verifying mails getting error cause of missing trash

### ISSUE THREAD

**Issue by evilmumi** [novskey/PalletTown#8]
please take a look on translations
trash is in other languages with other names
like in german 'Papierkorb'
can you add this?

error message we get:

`[21:31:45] Waiting 4 minutes to verify emails
javax.mail.FolderNotFoundException: [Gmail]/Trash not found
	at com.sun.mail.imap.IMAPFolder.checkExists(IMAPFolder.java:452)
	at com.sun.mail.imap.IMAPFolder.open(IMAPFolder.java:1040)
	at com.sun.mail.imap.IMAPFolder.open(IMAPFolder.java:973)
	at pallettown.EmailVerifier.verify(EmailVerifier.java:60)
	at pallettown.PalletTown.Start(PalletTown.java:108)
	at pallettown.PalletTown.run(PalletTown.java:420)
	at java.lang.Thread.run(Unknown Source)`

**Comment by parislarkins** [comment]
Yep, came across this issue last night. I'm adding a box in advanced settings to specify the name of trash bin. Other option is to use hotmail

**Comment by evilmumi** [comment]
@novskey thanks to do so. just wait for release :)

**Comment by parislarkins** [comment]
Fixed in latest release :)

**Comment by evilmumi** [comment]
@novskey still got error
`[21:01:05] Verified email and trashing, validate key: 45345334534

javax.mail.MessageRemovedException: Messages have been removed
	at com.sun.mail.imap.IMAPFolder.setFlags(IMAPFolder.java:1379)
	at pallettown.EmailVerifier.processMail(EmailVerifier.java:142)
	at pallettown.EmailVerifier.verify(EmailVerifier.java:82)
	at pallettown.PalletTown.Start(PalletTown.java:109)
	at pallettown.PalletTown.run(PalletTown.java:433)
	at java.lang.Thread.run(Unknown Source)
[21:01:05] Done!`

**Comment by parislarkins** [comment]
Does email verification still work though? It shouldn't affect anything

**Comment by evilmumi** [comment]
It should work. Can you allow to change the 4 Minute wait Time

**Comment by parislarkins** [comment]
Yep. I'll have it so it only waits the 4 minutes if you're using hotmail forwarded to gmail.
